#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-lumberjack
Version  : 1.0.9
Release  : 3
URL      : https://rubygems.org/downloads/lumberjack-1.0.9.gem
Source0  : https://rubygems.org/downloads/lumberjack-1.0.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
= Lumberjack
Lumberjack is a simple, powerful, and fast logging implementation in Ruby. It uses nearly the same API as the Logger class in the Ruby standard library and as ActiveSupport::BufferedLogger in Rails.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n lumberjack-1.0.9
gem spec %{SOURCE0} -l --ruby > rubygem-lumberjack.gemspec

%build
gem build rubygem-lumberjack.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
lumberjack-1.0.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/lumberjack-1.0.9
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/lumberjack-1.0.9.gem
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/DateRollingLogFile/after_roll-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/DateRollingLogFile/archive_file_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/DateRollingLogFile/cdesc-DateRollingLogFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/DateRollingLogFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/DateRollingLogFile/roll_file%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/LogFile/cdesc-LogFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/LogFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/LogFile/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Null/cdesc-Null.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Null/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Null/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/after_roll-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/archive_file_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/cdesc-RollingLogFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/keep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/reopen_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/RollingLogFile/roll_file%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/SizeRollingLogFile/archive_file_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/SizeRollingLogFile/cdesc-SizeRollingLogFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/SizeRollingLogFile/max_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/SizeRollingLogFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/SizeRollingLogFile/roll_file%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/Buffer/cdesc-Buffer.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/before_flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/buffer_size%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/buffer_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/cdesc-Writer.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/stream%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/Writer/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/cdesc-Device.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/cleanup_files%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/do_once-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Device/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/ExceptionFormatter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/ExceptionFormatter/cdesc-ExceptionFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/InspectFormatter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/InspectFormatter/cdesc-InspectFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/PrettyPrintFormatter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/PrettyPrintFormatter/cdesc-PrettyPrintFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/PrettyPrintFormatter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/PrettyPrintFormatter/width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/StringFormatter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/StringFormatter/cdesc-StringFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/cdesc-Formatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Formatter/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/cdesc-LogEntry.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/progname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/severity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/severity_label-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/LogEntry/unit_of_work_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/debug%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/device-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/error%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/fatal%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/fatal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/formatter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/info%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/last_flushed_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/level%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/progname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/set_progname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/silence-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/silencer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/unknown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/warn%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Logger/warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Rack/UnitOfWork/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Rack/UnitOfWork/cdesc-UnitOfWork.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Rack/UnitOfWork/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Rack/cdesc-Rack.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Severity/cdesc-Severity.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Severity/label_to_level-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Severity/level_to_label-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Template/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Template/cdesc-Template.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/Template/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/cdesc-Lumberjack.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/unit_of_work-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/Lumberjack/unit_of_work_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/lumberjack-1.0.9/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/MIT_LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/date_rolling_log_file.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/log_file.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/null.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/rolling_log_file.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/size_rolling_log_file.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/device/writer.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/formatter/exception_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/formatter/inspect_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/formatter/pretty_print_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/formatter/string_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/log_entry.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/rack.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/rack/unit_of_work.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/severity.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib/lumberjack/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/date_rolling_log_file_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/log_file_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/null_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/rolling_log_file_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/size_rolling_log_file_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/device/writer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/formatter/exception_formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/formatter/inspect_formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/formatter/pretty_print_formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/formatter/string_formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/log_entry_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/logger_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/lumberjack_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/rack/unit_of_work_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/severity_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/lumberjack-1.0.9/spec/template_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/lumberjack-1.0.9.gemspec
